// How subcontractors title their SWMS, and the job step groups (kinds) each title should tick
// when typed into the Task box. Written for the owner to read and change.
//
// Each row: [what is typed, kinds it must tick, kinds it must not tick, type, note]
//   kinds it must tick: space separated, all needed; "a|b" means either a or b will do.
//   type '': a task the library has job steps for.
//   type 'gap': the library has no job steps for the main work. Nothing is forced onto it;
//     it passes as long as it ticks none of the kinds it must not tick. Listed for the owner.
//   type 'general': not one task (a tool, PPE, a document, a whole trade, or wording that could
//     mean several trades). It passes as long as it ticks none of the kinds it must not tick.
//
// TITLES: the 343 real SWMS titles in the evidence file (scratchpad/catalogue/evidence-titles.json),
// in its order. LABELS: the 285 task labels of the draft trade catalogue (scratchpad/catalogue/trades).
// PROBE: the 65 titles typed in the goal 1 review (scratchpad/goal-review/goal-1.md, finding 8).

const TITLES = [
  ['Conduit Installation, Placed Prior to Pouring Concrete', 'castIn', '', '', 'electrical: conduit on the deck before the pour'],
  ['Conduit Installation, In Ground', 'trench', '', '', 'conduit laid in a trench'],
  ['Conduit Installation, Walls and Ceilings', 'fitOff', '', '', 'rough-in'],
  ['Cable and Ladder Tray Installation', 'containment', '', '', ''],
  ['Using Portable Ladders', 'ladderUse', '', '', ''],
  ['Installing Light Fittings', 'fitOff', '', '', ''],
  ['Installation of Switchboards', 'commissioning', '', '', 'deliver and place switchboards'],
  ['Installation of Lighting Looms', 'fitOff', '', '', ''],
  ['Installation of Cable Supports', 'containment', '', '', ''],
  ['Installation of Mains', '', 'waterConnection', 'general', 'electrical consumer mains or water mains: the title alone does not say'],
  ['Installation of Switchboard Connections', 'commissioning', '', '', ''],
  ['Installation of SubMains', 'cablePull', '', '', ''],
  ['Installation of Power and Light Cabling', 'fitOff', '', '', ''],
  ['Installation of Power Points', 'fitOff', '', '', ''],
  ['Manual Handling', '', '', 'general', ''],
  ['Working with Elevated Work Platforms', 'ewp', '', '', ''],
  ['Erecting and Using Mobile Scaffolds', 'mobileScaffold', '', '', ''],
  ['Dismantling Mobile Scaffolds', 'mobileScaffold', '', '', ''],
  ['Working at Heights', '', '', 'general', ''],
  ['Installation of New Work in Existing Switchboards', 'isolation', '', '', 'work near energised parts'],
  ['Working in Risers', '', '', 'gap', 'work in open service risers'],
  ['Installation of Pyrotenax, (MIMS) Cable', 'cablePull', '', '', 'mineral insulated cable pulled and fixed'],
  ['Isolation and Testing of Energy Sources', 'isolation', '', '', ''],
  ['Installation of Equipment Racks', 'commsRoom', 'palletRacking', '', 'communications racks'],
  ['Installation of Fibre Optic Cable', 'fibre', '', '', ''],
  ['Installation of Trunk Cabling', 'ictCabling', '', '', 'communications backbone cabling'],
  ['Installation of Outlet Cabling', 'fitOff|ictCabling', '', '', 'power or data outlets'],
  ['Installation of Outlets', 'fitOff|ictCabling', '', '', 'power or data outlets'],
  ['Working on Energised Low Voltage Equipment / Apparatus', 'isolation', '', '', ''],
  ['Installing Ceiling Mounted Lights and Speakers', 'fitOff', 'speakerHang', '', 'ceiling speakers are not hung from a roof structure'],
  ['Installation of New Racks / Cabinets', 'commsRoom', 'carpJoinery', '', 'communications racks, not kitchen cabinets'],
  ['Heat Shrink Cable Joints and Lugs', '', '', 'gap', 'low voltage cable jointing with a gas torch'],
  ['Installation of SELV Cabling [Data/Security/Nurse Call, etc]', 'ictCabling', '', '', ''],
  ['Installation of Data / TV / Nurse Call Points', 'ictCabling', 'fixtures', '', 'TV points are outlets, not wall-mounted TVs'],
  ['Installing light poles', 'poleErect', '', '', ''],
  ['Trenching with a small excavator', 'trench', '', '', ''],
  ['Installation of Grid Connected Photovoltaic System', 'solarPV', '', '', ''],
  ['Energise and Commission Installation', 'commissioning', '', '', ''],
  ['Test & Tag Electrical Equipment', 'testTag', '', '', ''],
  ['PPE', '', '', 'general', ''],
  ['Step Ladder', 'ladderUse', '', '', ''],
  ['A LADDER', 'ladderUse', '', '', 'A-frame ladder'],
  ['P LADDER', 'ladderUse', '', '', 'platform ladder'],
  ['S LADDER', 'ladderUse', '', '', 'straight ladder'],
  ['SCAFFOLD', '', '', 'general', 'erecting a scaffold or working from one: the title alone does not say'],
  ['SCISSOR LIFT', 'ewp', '', '', ''],
  ['BOOM', '', '', 'general', 'a boom lift or a concrete boom: the title alone does not say'],
  ['DUCT LIFTER', '', '', 'general', 'plant item'],
  ['ELECTRICAL POWER TOOLS', '', '', 'general', 'tool'],
  ['HAND TOOLS', '', '', 'general', 'tool'],
  ['VOLT TESTER', '', '', 'general', 'tool'],
  ['DROP SAW', '', '', 'general', 'tool'],
  ['WELD - CONFINE', 'hotWork|steelWeld', '', '', 'welding in a confined space'],
  ['WELDING - ELECARC', 'hotWork|steelWeld', '', '', ''],
  ['WELDING', 'hotWork|steelWeld', '', '', ''],
  ['ROUGH INS', '', '', 'general', 'electrical, plumbing or air conditioning rough-in: the title alone does not say'],
  ['REMOVALS', '', '', 'general', ''],
  ['ACCESS INVESTIGATING AIR CONDITIONING', '', '', 'gap', 'finding faults on air conditioning units inside the building'],
  ['DISCONNECTION OF AIR CONDITIONERS', 'servicesStrip', '', '', 'disconnect and remove existing units'],
  ['RECONNECTION', '', '', 'general', ''],
  ['INSTALL DUCTWORK CONCRETE & OR CEILING', 'ductwork', '', '', ''],
  ['INSTALLING DUCT WORK', 'ductwork', '', '', ''],
  ['INSTALLING VERTICAL DUCT WORK', 'ductwork', '', '', ''],
  ['INSTALLING DUCT WORK TO UNDERSIDE OF CONCRETE', 'ductwork', '', '', ''],
  ['REPAIRING DAMAGED DUCT WORK', 'ductwork', '', '', ''],
  ['MANUAL HANDLING', '', '', 'general', ''],
  ['INSTALLING PVC/COPPER PIPEWORK INTO GROUND', 'trench', '', '', 'pipework laid in the ground'],
  ['INSTALLING PAIR COIL/REFRIGERATE PIPING', 'mechPipework|refrigerantPipework', '', '', ''],
  ['INSTALLING TOILET EXHAUST FAN', 'ductwork', 'plumbingFitOff', '', 'a fan in a toilet ceiling is not a toilet suite'],
  ['INSTALLING CONDENSATE FLEXI PIPING', 'mechPipework', '', '', ''],
  ['INSTALLING CONDENSATE PIPING - RIGID', 'mechPipework', '', '', ''],
  ['INSTALLING COPPER / PVC PIPEWORK TO CONCRETE SLAB', 'mechPipework|hydraulicRisers', '', '', 'pipework fixed to the slab soffit'],
  ['INSTALLING FCU TO CONCRETE', 'fanCoil', '', '', ''],
  ['ENERGISING', 'commissioning', '', '', ''],
  ['CONDUIT INSTALLATION BEFORE CONCRETE', 'castIn', '', '', ''],
  ['INSTALLING CABLE TO CONCRETE', 'containment|fitOff', '', '', ''],
  ['INSTALLING CABLE SUPPORTS', 'containment', '', '', ''],
  ['INSTALLING OUTLET CABLING', 'fitOff|ictCabling', '', '', ''],
  ['INSTALLING OUTLETS', 'fitOff|ictCabling', '', '', ''],
  ['WORKING ON ENERGIZED LOW VOLTAGE EQUIPMENT', 'isolation', '', '', ''],
  ['ISOLATION AND TESTING OF ENERGY SOURCES', 'isolation', '', '', ''],
  ['INSTALLION OF NEW WORK IN EXISTING SWITCHBOARD', 'isolation', '', '', ''],
  ['INSTALLATION OF NEW SWITCHBOARD CONNECTIONS', 'commissioning', '', '', ''],
  ['INSTALLATION OF SWITCHBOARDS', 'commissioning', '', '', ''],
  ['INSTALLATION OF MAINS', '', 'waterConnection', 'general', 'electrical consumer mains or water mains'],
  ['TESTING AND TAGGING ELECTRICAL EQUIPMENT', 'testTag', '', '', ''],
  ['INSTALLING CONDUIT IN GROUND', 'trench', '', '', ''],
  ['INSTALLING CONDUIT WALLS AND CEILINGS', 'fitOff', '', '', ''],
  ['INSTALL CABLE AND LADDER TRAY', 'containment', '', '', ''],
  ['PROGRAMMING THE BMS SYSTEM', '', '', 'general', 'computer work'],
  ['R 410 A REFRIGERANT GAS', '', '', 'general', 'substance'],
  ['ACETYLENE', '', '', 'general', 'substance'],
  ['OXYGEN', '', '', 'general', 'substance'],
  ['NITROGEN', '', '', 'general', 'substance'],
  ['USING FIRECAULK', '', '', 'general', 'substance'],
  ['USING MAPP SUPER GAS', '', '', 'general', 'substance'],
  ['USING SEAL N FLEX', '', '', 'general', 'substance'],
  ['SWMS Work on or near electrical installations', 'isolation', '', '', ''],
  ['SWMS work on or near gas distribution lines', '', '', 'gap', 'work near live gas mains'],
  ['SWMS Asbestos Removal & Minor Damage', 'asbestos', '', '', ''],
  ['SWMS Demolition', 'demolition', '', '', ''],
  ['SWMS for Work at Heights and Being Struck by Falling Objects', '', '', 'general', ''],
  ['SWMS work carried out in contaminated environment', '', '', 'general', 'high risk category'],
  ['SWMS for work include the use of Mobile Plant', 'sitePlant', '', '', ''],
  ['SWMS Work on or near a Excavation', 'trench', '', '', ''],
  ['SWMS Works on or near to Roadway or Railway', 'road railCorridor', '', '', ''],
  ['SWMS Works on or Near Water', 'water', '', '', ''],
  ['SWMS Work requiring Structural Alteration and Temporary Support', 'propping', '', '', ''],
  ['SWMS Work in a Confined Space', 'confined', '', '', ''],
  ['SWMS Power Tool Use', '', '', 'general', 'tool'],
  ['SWMS Landscaping', 'landscape', '', '', ''],
  ['SWMS Bricklaying', 'masonryLay', '', '', ''],
  ['Window Installation', 'windowInstall', '', '', ''],
  ['SWMS for Painting', 'painting', '', '', ''],
  ['SWMS Floor Wall Tiling', 'tileLay', '', '', ''],
  ['SWMS Fix and Eave Carpentry', 'carpJoinery', '', '', 'fix-out carpentry'],
  ['SWMS Plasterboard Linings', 'plasterSheets', '', '', ''],
  ['Working at Heights', '', '', 'general', ''],
  ['Hot Work - Grinding', 'hotWork', '', '', ''],
  ['Sub Floor Preparation', 'floorGrind|floorLevel', '', '', 'preparing floors for floor coverings'],
  ['Plastering', 'plasterSheets|rendering', '', '', ''],
  ['Painting', 'painting', '', '', ''],
  ['Demolition - Non-Structural', 'stripOut|officeStrip', 'demolition', '', 'strip-out, not structural demolition'],
  ['Carpentry', 'carpentryWork', '', '', 'whole trade'],
  ['Building Site Clean up', 'wasteRemoval', '', '', ''],
  ['Working on or adjacent to roads or railways', 'road railCorridor', '', '', ''],
  ['Risk of a person falling more than 2 metres', '', '', 'general', ''],
  ['Working in over or adjacent to water', 'water', '', '', ''],
  ['Working in or near confined space', 'confined', '', '', ''],
  ['Working in or around trenches & Excavation', 'trench', '', '', ''],
  ['Operating Mobile Plant', 'sitePlant', '', '', ''],
  ['Overhead Power', 'power', '', '', ''],
  ['Hot Works', 'hotWork', '', '', ''],
  ['Loading & Unloading Mobile Plant', 'heavyHaulage', '', '', 'floating plant: load restraint and haulage; the earthmoving plant step has the float ramp lines'],
  ['Moxy Moving Logs & Branches', '', '', 'general', 'plant item'],
  ['Bridge Installation', '', '', 'general', 'whole package'],
  ['Securing Poles and Transportation', '', '', 'general', 'load restraint'],
  ['Installation of Poles', 'poleErect', '', '', ''],
  ['Vehicle Loading Crane', 'loaderCrane', '', '', ''],
  ['Vegetation Clearing & Mulching', 'vegClearing', '', '', ''],
  ['Hazardous Tree Removal & Chainsaw Operations', 'treeRemoval', '', '', ''],
  ['Crane Truck', 'loaderCrane', '', '', ''],
  ['Dolly', '', '', 'general', 'plant item'],
  ['Dozer', 'earthworks', '', '', ''],
  ['End Loader', 'earthworks', '', '', ''],
  ['Excavator', 'earthworks', '', '', ''],
  ['Flat Drum Roller', 'earthworks|roadPlant', '', '', ''],
  ['Grader', 'earthworks', '', '', ''],
  ['Low Loader Trailer', 'heavyHaulage', '', '', ''],
  ['Moxy', 'earthworks', '', '', 'articulated dump truck'],
  ['Mulcher', 'vegClearing', '', '', ''],
  ['Posi Track', 'smallPlant', '', '', ''],
  ['Scraper', 'earthworks', '', '', ''],
  ['Semi Tipper', 'heavyHaulage|spoilManage|earthworks', '', '', ''],
  ['Side by Side Buggy', '', '', 'general', 'plant item'],
  ['Side Tipper', 'heavyHaulage|spoilManage|earthworks', '', '', ''],
  ['Slasher', '', '', 'general', 'plant item'],
  ['Spray Truck', '', '', 'general', 'bitumen sprayer or water spray: the title alone does not say'],
  ['Tip Truck', 'heavyHaulage|spoilManage|earthworks', '', '', ''],
  ['Truck and Dog', 'heavyHaulage|spoilManage|earthworks', '', '', ''],
  ['Water Truck', 'earthworks', '', '', 'the earthmoving plant step has the water cart lines'],
  ['Bridge Construction', '', '', 'general', 'whole package'],
  ['Civil Construction Activities', '', '', 'general', 'whole trade'],
  ['Clearing', 'vegClearing', '', '', 'civil site clearing'],
  ['Gravel Haulage', 'heavyHaulage|spoilManage', '', '', ''],
  ['Stripping Soil', 'earthworks', '', '', 'topsoil stripping'],
  ['Bulk Earthworks', 'earthworks', '', '', ''],
  ['Storm Water Drainage', 'trench', '', '', ''],
  ['Build Gully Pits', 'trench|tankPlace', '', '', ''],
  ['Build Manholes', 'trench|tankPlace', '', '', ''],
  ['Sewer Construction', 'trench', '', '', ''],
  ['Subgrade Preparation', 'earthworks', '', '', ''],
  ['Subgrade Replacement', 'earthworks', '', '', ''],
  ['Sub Base Material', 'gravelLay|roadPlant', '', '', 'granular pavement'],
  ['Sub Soil Drainage', 'trench', '', '', ''],
  ['Re-Sheeting Roads', 'gravelLay|roadPlant', 'roof roofStrip', '', 'gravel road resheeting, not roofing'],
  ['Road Stabilisation', 'roadPlant', '', '', ''],
  ['Driving Heavy Vehicles', 'heavyHaulage', '', '', ''],
  ['Plant Isolation', '', '', 'general', ''],
  ['3.1-101 SWMS High Risk - Blower Truck Operations', 'blowerTruck', '', '', ''],
  ['3.1-101 SWMS High Risk - Blower Truck Operations - Heights Work', 'blowerTruck', '', '', ''],
  ['3.1-102 SWMS High Risk - Slinger Truck - Site Specific', 'slingerTruck', '', '', ''],
  ['SWMS001 Movement of Mobile Plant', 'sitePlant', '', '', ''],
  ['SOP002 (title not given)', '', '', 'general', ''],
  ['Excavation carried out in or near a shaft/trench > 1.5m Depth', 'trench', '', '', ''],
  ['Road works', 'road', '', '', ''],
  ['Work carried out on or near energised electrical installations or services', 'isolation', '', '', ''],
  ['SWMS 03: Installation of Linings to Partition Walls and Ceilings', 'plasterSheets', '', '', ''],
  ['SWMS 10 / Installation of Insulated Wall Panels', '', 'wallPanels', 'gap', 'insulated sandwich panel walls in a fit-out (the coolroom step is for coolrooms)'],
  ['SWMS 20 / Installation of Under Slab Insulation', 'insulation', '', '', ''],
  ['SWMS No. 7: Installing Under Slab Insulation', 'insulation', '', '', ''],
  ['Manual Handling', '', '', 'general', ''],
  ['Mobile Scaffolds', 'mobileScaffold', '', '', ''],
  ['EWPs', 'ewp', '', '', ''],
  ['Forklift', 'forklift', '', '', ''],
  ['Electric Pallet Jack', '', '', 'general', 'plant item'],
  ['Scissor lift operation', 'ewp', '', '', ''],
  ['SWMS 14 Painting & Decorating', 'painting', '', '', ''],
  ['SWMS 9 Electrical isolation - Lock Out Tag Out procedure when accessing roof cavities to perform non-electrical work', 'roofSpace', '', '', ''],
  ['SWMS 2 - Power Tools', '', '', 'general', 'tool'],
  ['SWMS 3 - Hand Tools', '', '', 'general', 'tool'],
  ['SWMS 4 - Ladder Safety', 'ladderUse', '', '', ''],
  ['SWMS 12 - Working at Heights', '', '', 'general', ''],
  ['STEEL ERECTION', 'steelErect', '', '', ''],
  ['Crane - General Use', 'craneInterface|crane', '', '', ''],
  ['Work Platforms', '', '', 'general', ''],
  ['Working at Heights', '', '', 'general', ''],
  ['Manual Handling', '', '', 'general', ''],
  ['Power Tools - General use', '', '', 'general', 'tool'],
  ['SWMS No.1 Crane Setup/Pack up', 'craneInterface|crane', '', '', ''],
  ['Lifting Concrete Items', 'craneInterface|crane', '', '', 'crane crew lifting loads'],
  ['Lifting Scaffold and Formwork Materials', 'craneInterface|crane', 'formwork scaffold', '', 'the crane crew lifts the loads; it does not build the formwork'],
  ['Lifting Steel components', 'craneInterface|crane', '', '', ''],
  ['Site Specific Job Docket (with risk assessment and toolbox talk)', '', '', 'general', 'document'],
  ['Formwork (Supply & Fix formwork)', 'formwork', '', '', ''],
  ['Reinforcement (Supply & Place Reinforcement)', 'reo', '', '', ''],
  ['Formwork Construction', 'formwork', '', '', ''],
  ['SWMS 4. HOT WORKS - Including Cutting & Drilling', 'hotWork', '', '', ''],
  ['Safe Work Method Statement Air Conditioning', '', '', 'general', 'whole trade'],
  ['Installation of new line marking/road markings and/or maintenance of existing line marking/road markings', 'lineMarking', '', '', ''],
  ['Line marking, Raised Pavement Markers, Signs & Traffic Counters Installation', 'lineMarking', '', '', ''],
  ['Mix mortar and lay bricks and blocks to Australian Standard', 'masonryLay', '', '', ''],
  ['SWMS No. 1: Interior Fitout', '', '', 'general', 'whole trade'],
  ['Shopfitting', '', '', 'general', 'whole trade'],
  ['Waterproofing Bathrooms - liquid applied membranes', 'wpLiquid', '', '', ''],
  ['Glass Wool Installation', 'insulation', '', '', ''],
  ['SWMS - INSULATION', 'insulation', '', '', ''],
  ['Safe Working Method Statement of Competency', '', '', 'general', 'document'],
  ['Daily job specific risk assessment sheet', '', '', 'general', 'document'],
  ['SWI: Compressor', '', '', 'general', 'tool'],
  ['SWI: Demolition hammer', '', 'demolition structureDemolition', 'general', 'a jackhammer, not demolishing a building'],
  ['SWI: Drills', '', '', 'general', 'tool'],
  ['SWI: Gas cylinders', '', 'gasCylinders', 'general', 'tool'],
  ['SWI: Generator', '', '', 'general', 'tool'],
  ['SWI: Load restraint', '', '', 'general', ''],
  ['SWI: Trailer towing', '', '', 'general', ''],
  ['SWI: Blower', '', 'blowerTruck', 'general', 'a leaf blower, not a blower truck'],
  ['SWI: Heat stress', 'heatWork', '', '', ''],
  ['SWI: Power line clearance', 'power', '', '', ''],
  ['Corporate HRCW SWMS', '', '', 'general', 'document'],
  ['Solar PV system installation - solar panel installation on roof', 'solarPV', '', '', ''],
  ['General concreting (kerbs and channels)', 'kerbInstall', '', '', ''],
  ['Asbestos - Non Friable - Removal', 'asbestos', '', '', ''],
  ['Asbestos - Friable - Removal', 'asbestos', '', '', ''],
  ['Excavations, trenching and footings', 'trench', '', '', ''],
  ['Removal and disposal of friable and non-friable asbestos containing materials', 'asbestos', '', '', ''],
  ['SWMS Master (mobile crane)', 'craneInterface|crane', '', '', ''],
  ['Hardstand Operations', '', '', 'general', 'boat yard, not construction'],
  ['General Lifting', 'craneInterface|crane', '', '', ''],
  ['Demolition of House and Sub-structures', 'demolition|structureDemolition', '', '', ''],
  ['Asbestos Removal Control Plan (Hazardous Material Management Plan)', 'asbestos', '', '', ''],
  ['Asbestos management, removal and transportation', 'asbestos', '', '', ''],
  ['The installation and or adjustment & removal of a pre-fabricated modular steel scaffolding system', 'scaffold', '', '', ''],
  ['Condensed SWMS - planting, auger use, brush cutter use, jute matting, landscaping and turf laying', 'landscape', '', '', ''],
  ['Auger - Hand Held - Petrol fueled', '', '', 'general', 'tool'],
  ['Operation of Emergency Response Procedure - Vacuum Truck', '', '', 'general', 'emergency procedure'],
  ['SWMS for Hydro Excavations', 'vacExcavation', '', '', ''],
  ['Work Method Statement - Demolition, Residential Flat Building', 'demolition|structureDemolition', '', '', ''],
  ['Asbestos/Hazardous Materials Destructive Survey', '', '', 'gap', 'hazardous materials survey and sampling (it ticks the asbestos removal steps, which cover only part of it)'],
  ['Delivery of Concrete', '', '', 'gap', 'concrete agitator truck delivery'],
  ['General Lifting', 'craneInterface|crane', '', '', ''],
  ['Concrete Boom Pumping', 'concrete', '', '', ''],
  ['High pressure water cleaner', 'pressureClean|hydroBlast', '', '', ''],
  ['Safe Operation of HIAB Loader Crane (3.5 Tonne) - Safe Operation of Vehicle Loading Cranes', 'loaderCrane', 'earthworks', '', 'a loader crane is not an earthmoving loader'],
  ['Operation of Water Truck', 'earthworks', '', '', 'the earthmoving plant step has the water cart lines'],
  ['Plumbing and drainage', '', '', 'general', 'whole trade'],
  ['Crane Truck (vehicle loading crane, including access to and work within the rail corridor)', 'loaderCrane railCorridor', '', '', ''],
  ['Metal Roofing Installation', 'roof', '', '', ''],
  ['Protection Officer within the ARTC corridor', 'railCorridor', '', '', ''],
  ['Moving and use of Saferoads Solar Lighting Product - 320W Solar Pole', 'solarLights', '', '', ''],
  ['Erection, dismantling and use of fixed scaffold', 'scaffold', '', '', ''],
  ['Temporary Generator Installation', 'generatorConnect', 'generatorPlant', '', 'a temporary generator, not a permanent one'],
  ['Installation of Temporary Electrical Services', 'tempPower', '', '', ''],
  ['Fuel trailer refuelling', 'refuelPlant', '', '', ''],
  ['Lifting Portable Buildings', 'portableBuilding', '', '', ''],
  ['Security cabling (JSEA/SWMS)', 'ictCabling|securityDevices', '', '', ''],
  ['Remove topsoil and relocate; prepare pen foundation (gravel compaction); feed roads; cattle lanes and drains', 'earthworks', '', '', ''],
  ['Electrical SWMS: Safe working on or near (within 500mm of) low-voltage electrical installations', 'isolation', '', '', ''],
  ['Volunteers - Painting, Outdoor Cleaning and Graffiti Removal', 'graffitiRemoval painting', '', '', ''],
  ['Project - Citizen Science for volunteers with Pandemic Influenza Action Plan', '', '', 'general', 'not construction'],
  ['Operations blasting', 'blasting', '', '', ''],
  ['Work Method Statement - Managing the Risk of Electricity', '', '', 'general', ''],
  ['Work Method Statement - Managing the Risk of Plant', '', '', 'general', ''],
  ['Work Method Statement - Managing the Risk of Falls (ladders)', '', '', 'general', ''],
  ['Work Method Statement - Managing the Risk of Falls (guard rails, EWP, restraint, arrest)', '', '', 'general', ''],
  ['Mandatory SWMS 100 - Operation of Vacuum Truck', 'vacExcavation', '', '', ''],
  ['SWMS-010 (title not given)', '', '', 'general', ''],
  ['Other contractor SWMS for work from the scissor lift', 'ewp', '', '', ''],
  ['Delivery of Reinforcement Steel & Accessories Safe Work Method Statement (SWMS) Rev 2', 'reo', '', '', ''],
  ['SWMS (thin)', '', '', 'general', ''],
  ['SWMS Piling Works', 'pilingRig', '', '', ''],
  ['SWMS Piling Machine Assembly', 'pilingPlatform', '', '', ''],
  ['Precision Formwork: form work', 'formwork', '', '', ''],
  ['SWMS Formwork 2021', 'formwork', '', '', ''],
  ['Steel Fixing', 'reo', '', '', ''],
  ['B Grade Bricklayers: SWMS sample bricklaying', 'masonryLay', '', '', ''],
  ['STT DC3 SWMS WET SPRINKLER', 'fireAtHeight', '', '', ''],
  ['Safety Line Marking: cold applied plastic', 'lineMarking', '', '', ''],
  ['RAAF linemarking', 'lineMarking', '', '', ''],
  ['Cabinetry joinery', 'carpJoinery', '', '', ''],
  ['Interior fitouts', '', '', 'general', 'whole trade'],
  ['Waterproofing', '', '', 'general', 'whole trade'],
  ['Precast and Tilt Up Panels (procedure)', 'precast', '', '', ''],
  ['Air condition Units and Electrical installation', 'splitInstall|plantLift|ductwork', '', '', ''],
  ['Form reinforce and pour concrete footings/pedestals/pathways/driveways/retainer walls/including detailed excavation', 'slabGround slabPour detailDig', '', '', ''],
  ['Construction, S1 Commissioning and Repair on Precinct A (load centre)', '', '', 'general', 'project package'],
  ['ISS Demolition Works', 'demolition', '', '', ''],
  ['Precinct A Electrical Construction Works: Trenching, Conduit/Pit Installation, Cable Support Installation, Cable Installation, Equipment Installation, Cable Terminations', 'trench containment', '', '', ''],
  ['Gabion building and installation', 'retainingWall', '', '', 'the retaining wall group has a gabion basket step'],
  ['Plumbing works (trenching, pipe installation, roofing & down pipe installation, sewer line poly welding & brazing, manhole & storm water pit installation)', 'trench', '', '', ''],
  ['PMT Bollard Works', 'bollards', '', '', ''],
  ['Precinct B Trenching, excavation and installation of electrical underground conduit', 'trench', '', '', ''],
  ['SWMS for each task and for the 18 high risk construction work categories (SR02)', '', '', 'general', 'document'],
  ['SWMS for personal fall protection equipment use (PS02)', '', '', 'general', ''],
  ['Removal of void protection (PS01)', 'edgeProtectionInstall', '', '', ''],
  ['Excavation and piling (PS07)', 'pilingRig', '', '', ''],
  ['Concrete pump planning (PS11 site establishment)', 'concrete', '', '', ''],
  ['Crane operations including anti-collision (PS17)', 'craneInterface|crane', '', '', ''],
  ['Precast and tilt-up: SWMS per task (PS27)', 'precast', '', '', ''],
  ['Power tools (PS28)', '', '', 'general', 'tool'],
  ['Explosive powered tools (PS28)', 'pdtFixing', '', '', ''],
  ['Hot works (PS34, PS39)', 'hotWork', '', '', ''],
  ['Confined space entry (PS39)', 'confined', '', '', ''],
  ['Electrical and plant isolation (PS40, PS41)', 'isolation', '', '', ''],
  ['Grid mesh removal (PS39)', '', '', 'gap', 'removing floor grid mesh and checker plate'],
  ['Work over water and diving (PS43)', 'water', '', '', ''],
  ['Unloading by delivery drivers (SR11)', '', '', 'general', ''],
  ['EWP use (PS16)', 'ewp', '', '', ''],
  ['Project standards with their own activity rules: scaffolding (PS03), loading and unloading (PS04), mini cranes (PS10), blasting (PS22), demolition (PS23), formwork (PS24), lasers (PS25), plant (PS26), asbestos (PS52)', '', '', 'general', 'a list of standards'],
  ['Live electrical work (GMR 4.2)', 'isolation', '', '', ''],
  ['Work near overhead lines, zones B and C (GMR 4.C)', 'power', '', '', ''],
  ['Excavation and ground penetration (GMR 2.2, 2.5)', 'trench', '', '', ''],
  ['Tunnelling (GMR 2.6)', 'tunnelWork', '', '', ''],
  ['Lifting operations (GMR 3.1)', 'craneInterface|crane', '', '', ''],
  ['Grid mesh and checker plate installation and removal (GMR 5.5)', 'accessSteel', '', '', ''],
  ['Roof sheeting from below or a solid platform after safety mesh (GMR 5d)', 'roof', '', '', ''],
  ['Temporary works installation and removal (GMR 7a)', '', '', 'general', ''],
  ['Work on rail (GMR 10.4)', 'railCorridor', '', '', ''],
  ['How We Work Standard 07: Formwork (RCo-WS-07)', 'formwork', '', '', ''],
  ['How We Work Standard: Temporary works', '', '', 'general', ''],
  ['How We Work Standard: Work at height', '', '', 'general', ''],
  ['How We Work Standard: Manual handling', '', '', 'general', ''],
  ['How We Work Standard: PPE', '', '', 'general', ''],
];

const LABELS = [
  // Asbestos removal
  ['Non-friable asbestos removal (Class B)', 'asbestos', '', '', ''],
  ['Friable asbestos removal (Class A) in an enclosure', 'asbestos', '', '', ''],
  ['Asbestos in soil, pits and ducts', 'asbestos asbestosPits', '', '', ''],
  ['Hazardous materials survey and sampling', '', '', 'gap', 'hazardous materials survey and sampling'],
  ['Lead paint, SMF and PCB removal', 'leadPaint', '', '', ''],
  // Bridges
  ['Bridge substructure: footings, pile caps, abutments and wingwalls', 'formwork reo concrete', '', '', ''],
  ['Piers, columns and headstocks', 'formwork reo concrete', '', '', ''],
  ['Girder erection: precast concrete or steel girders', 'precast|steelErect', '', '', ''],
  ['Bridge deck: deck units or formwork, reo and pour', 'formwork reo concrete', '', '', ''],
  ['Bridge bearings: install and replace', 'bridgeBearings', '', '', ''],
  ['Bridge barriers, parapets and expansion joints', 'roadBarrier', '', '', ''],
  ['Post-tensioning of bridge elements', 'stressing', '', '', ''],
  ['Bridge work over or next to water', 'water', '', '', ''],
  ['Temporary bridges, falsework towers and working platforms', 'tempBridge formwork', '', '', ''],
  ['Bridge maintenance and repair over traffic or rail', 'workAbove', '', '', ''],
  // Carpentry and joinery
  ['Door frames, doors and hardware', 'doorHang', '', '', ''],
  ['Joinery and cabinetry installation', 'carpJoinery', '', '', ''],
  ['Fix-out: skirtings, architraves, timber linings and wall panelling', 'carpJoinery', '', '', ''],
  ['Toilet partitions, lockers, operable walls and bathroom accessories', 'fixtures', 'plumbingFitOff', '', ''],
  ['Timber wall, floor and roof framing', 'carpFraming|houseFraming', '', '', ''],
  ['Timber stairs, handrails, screens and decking at open edges', 'carpEdge', '', '', ''],
  // Civil earthworks
  ['Site clearing, grubbing and topsoil stripping', 'vegClearing', '', '', ''],
  ['Bulk earthworks: cut, fill and compaction', 'earthworks', '', '', ''],
  ['Detailed excavation for footings, pits and pile caps', 'detailDig', '', '', ''],
  ['Trenching for services, including trenches deeper than 1.5 m', 'trench', '', '', ''],
  ['Locating and exposing services by potholing or vacuum excavation', 'vacExcavation', '', '', ''],
  ['Rock breaking and ripping', 'rockBreak', '', '', ''],
  ['Spoil haulage, stockpiles and tipping', 'spoilManage', '', '', ''],
  ['Ground improvement: soft spot replacement, impact rolling and lime or cement treatment', 'impactRoller|earthworks', 'groundImprove', '', 'no rig: the ground improvement rig step is for stone columns and the like'],
  ['Erosion and sediment controls', '', '', 'gap', 'erosion and sediment controls'],
  ['Floating, loading and unloading plant', 'heavyHaulage', '', '', 'floating plant: load restraint and haulage'],
  ['Earthworks in or next to waterways and creek crossings', 'earthworks water', '', '', ''],
  // Cleaning
  ["Builders' clean and final clean", 'cleaning', '', '', ''],
  ['Window and facade cleaning', 'cleaningHeight', '', '', ''],
  ['Pressure cleaning and water blasting', 'pressureClean|hydroBlast', '', '', ''],
  ['Acid washing and chemical removal of mortar and render', 'cleaning', 'rendering', '', 'removing render is not rendering'],
  ['Site clean-ups and waste removal during construction', 'wasteRemoval', '', '', ''],
  // Concreting
  ['Placing and finishing concrete on suspended slabs, columns and walls', 'concrete', '', '', ''],
  ['Placing and finishing slabs on ground, footings and paths', 'slabGround slabPour', '', '', ''],
  ['Concrete pumping: boom pumps, line pumps and placing booms', 'concrete', '', '', ''],
  ['Concrete delivery by agitator truck', '', '', 'gap', 'concrete agitator truck delivery'],
  ['Patching, grinding and making good concrete', 'concreteRepair', '', '', ''],
  ['On-site concrete batch plant', 'processPlant', '', '', ''],
  // Cranes and rigging
  ['Mobile and crawler crane lifting', 'craneInterface|crane', '', '', ''],
  ['Tower crane erection, climbing and dismantling', 'towerCraneErect', '', '', ''],
  ['Tower crane operation and dogging', 'craneInterface|towerCrane', '', '', ''],
  ['Crawler crane assembly and dismantling', 'craneAssembly', '', '', ''],
  ['Dual and heavy lifts under an engineered lift plan', 'dualLift', '', '', ''],
  ['Vehicle loading cranes and crane trucks', 'loaderCrane', '', '', ''],
  ['Rigging: loading platforms, chain blocks and moving plant on skates', 'loadOut', '', '', ''],
  ['Lifting people in a crane workbox', 'craneInterface|crane', '', '', ''],
  // Demolition and strip-out
  ['Internal strip-out (soft strip)', 'stripOut|officeStrip', '', '', ''],
  ['Building demolition: roof removal, machine demolition and load-out', 'demolition', '', '', ''],
  ['Partial demolition and structural alterations in existing buildings', 'demolition', '', '', ''],
  // Electrical
  ['Construction power and temporary lighting', 'tempPower', '', '', ''],
  ['Temporary generators: place, connect, run and refuel', 'generatorConnect', '', '', ''],
  ['Cast-in conduits and boxes in slabs before the pour', 'castIn', '', '', ''],
  ['In-ground conduits, pits and cabling', 'trench', '', '', ''],
  ['Cable tray, ladder and supports at height', 'containment', '', '', ''],
  ['Rough-in: conduit and cabling in walls, ceilings and risers', 'fitOff', '', '', ''],
  ['Cable pulling: consumer mains and submains', 'cablePull', '', '', ''],
  ['Fit off: power, lighting and emergency lighting', 'fitOff', '', '', ''],
  ['Switchboards and distribution boards: deliver, install and terminate', 'commissioning', '', '', ''],
  ['Isolation, and work in existing live switchboards', 'isolation', '', '', ''],
  ['Testing, energising and commissioning', 'commissioning', '', '', ''],
  ['Cable jointing and terminations, LV and HV', 'hvTermination|commissioning', '', '', ''],
  ['High voltage: substations, transformers, ring main units and HV cable', 'substationEquip', '', '', ''],
  ['Permanent generators, UPS and central batteries', 'generatorPlant', '', '', ''],
  ['External lighting, light poles and street lighting', 'poleErect|trafficSignals', '', '', ''],
  ['Solar PV on roofs', 'solarPV', '', '', ''],
  ['Earthing and lightning protection', 'earthStakes lightningProtection', '', '', ''],
  ['Testing and tagging electrical equipment', 'testTag', '', '', ''],
  ['Core drilling, chasing and sealing penetrations', 'coreDrill', '', '', ''],
  ['Isolating and stripping out existing electrical services', 'servicesStrip', '', '', ''],
  // Facade and glazing
  ['Unitised curtain wall installation', 'panelInstall', '', '', ''],
  ['Stick curtain wall, glazed walls and shopfront framing', 'glassHandle|panelInstall|windowInstall', 'carpFraming', '', 'shopfront framing is aluminium glazing framing, not stud walls'],
  ['Windows, external doors and louvres', 'windowInstall', '', '', ''],
  ['Glass balustrades and handrails at open edges', 'balustradeEdge', '', '', ''],
  ['Internal glazing: glazed partitions, shower screens and mirrors', 'glassHandle', '', '', ''],
  ['Facade cladding panels: aluminium composite, metal and fibre cement', 'claddingInstall|panelInstall', '', '', ''],
  ['Facade sealing, repairs and glass replacement from a swing stage or BMU', 'swingStage', '', '', ''],
  // Fire services
  ['Sprinkler pipework and heads at height', 'fireAtHeight', '', '', ''],
  ['Hydrant and hose reel pipework and booster assemblies', 'fireAtHeight boosterInstall', '', '', ''],
  ['In-ground and under-slab fire mains', 'trench', '', '', ''],
  ['Fire pump rooms and fire water tanks', 'fireLive|pumpInstall', '', '', ''],
  ['Fire detection, alarm and occupant warning systems', 'fireAlarm', '', '', ''],
  ['Gas suppression and kitchen hood suppression', 'gasSuppression', '', '', ''],
  ['Work on live fire systems: isolations, impairments and connections', 'fireLive', '', '', ''],
  ['Testing and commissioning: hydrostatic, flow and discharge tests', 'pressureTest', '', '', ''],
  ['Core drilling, fire collars and sealing penetrations', 'passiveFire', '', '', ''],
  ['Portable extinguishers, blankets, signs and block plans', 'hoseReels', '', '', ''],
  ['Isolating and removing existing fire services', 'servicesStrip', '', '', ''],
  ['Routine inspection, testing and maintenance (AS 1851)', 'fireLive', '', '', ''],
  // Flooring
  ['Floor preparation: grinding, patching and levelling', 'floorGrind floorLevel', '', '', ''],
  ['Sheet vinyl, rubber and resilient flooring', 'floorLay', '', '', ''],
  ['Carpet and carpet tiles', 'floorLay', '', '', ''],
  ['Epoxy and polyurethane resin floor coatings', 'floorCoating', '', '', ''],
  ['Timber and engineered timber floors, sanding and coating', 'timberFloor floorSanding', '', '', ''],
  ['Raised access floors', 'accessFloor', '', '', ''],
  // Formwork
  ['Suspended slab and beam formwork: erect, strip and backprop', 'formwork', '', '', ''],
  ['Column, wall and stair formwork', 'formwork', '', '', ''],
  ['Jumpform and self-climbing core formwork', 'jumpform', '', '', ''],
  ['Perimeter safety screens: install, climb and remove', 'safetyScreens', '', '', ''],
  ['High falsework and load-bearing support scaffold', 'formwork', '', '', ''],
  ['Formwork for footings, ground slabs and edges', 'slabGround', '', '', ''],
  // Insulation
  ['Under slab (soffit) insulation boards', 'insulation', '', '', ''],
  ['Wall and ceiling batts, acoustic insulation and sisalation', 'insulation', '', '', ''],
  ['Insulation in the roof space of an existing building', 'insulation', '', '', 'the insulation step carries the roof space lines'],
  ['Sprayed insulation: polyurethane foam and sprayed fire or thermal coatings', 'sprayFoam', '', '', ''],
  // Landscaping
  ['Soft landscaping: soil, planting, mulch and turf', 'landscape', '', '', ''],
  ['Hard landscaping: paving, edging and landscape walls', 'paving', '', '', ''],
  ['Irrigation installation', 'shallowTrench', '', '', ''],
  ['Advanced and street tree planting', 'landscape', '', '', ''],
  ['Revegetation and batter planting', 'landscape', '', '', ''],
  ['Placing soil, mulch and aggregate with a blower or slinger truck', 'blowerTruck slingerTruck', '', '', ''],
  ['Podium, roof garden and green wall planting', 'landscapeLift|greenWall', '', '', ''],
  ['Landscape furniture, shade structures and playgrounds', 'playground|kitStructure|shadeSail', '', '', ''],
  // Lifts
  ['Lift shaft protection and access: landing openings, screens and shaft platforms', 'liftShaft', 'trench', '', 'a lift shaft is not an excavation'],
  ['Hoisting machines, rails and equipment into the shaft and machine room', 'liftLifting', 'trench', '', 'a lift shaft is not an excavation'],
  ['Installing rails, landing doors, car and counterweight', 'liftInstall|liftLifting', '', '', ''],
  ['Car top and pit work, testing and commissioning', 'liftCar', '', '', ''],
  ['Escalators and moving walks', 'escalatorInstall', '', '', ''],
  ['Lift modernisation and replacement in occupied buildings', 'liftCar|liftMotor', '', '', ''],
  ['Platform lifts, stair lifts and dumbwaiters', 'dumbwaiter platformLift|stairLiftInstall', '', '', ''],
  ['Construction use of a lift: jump lifts and temporary cars', '', '', 'gap', 'jump lifts and temporary lift cars during construction'],
  // Line marking
  ['Road line marking and raised pavement markers', 'lineMarking', '', '', ''],
  ['Car park, warehouse and sports court marking', 'lineMarking', '', '', ''],
  ['Line marking removal by grinding or water blasting', 'lineMarking', '', '', ''],
  ['Tactile ground surface indicators and anti-slip', 'tactileInstall', '', '', ''],
  // Masonry
  ['Reinforced blockwork walls and core filling', 'masonryLay masonryGrout', '', '', ''],
  ['Face brickwork and brick veneer', 'masonryLay', '', '', ''],
  ['Lightweight concrete (AAC) panel walls', 'claddingInstall|masonryLay', '', '', ''],
  ['Rendering and solid plastering', 'rendering', '', '', ''],
  ['Masonry repairs, repointing and restoration', 'repointing', '', '', ''],
  // Mechanical
  ['Mechanical plant: receive, move and set AHUs, chillers, cooling towers and condensers', 'plantLift', '', '', ''],
  ['Ductwork installation', 'ductwork', '', '', ''],
  ['Chilled water, heating water and condenser water pipework', 'mechPipework', '', '', ''],
  ['Refrigerant pipework: run, braze and pressure test', 'refrigerantPipework refrigerantTest', '', '', ''],
  ['Evacuating, charging and recovering refrigerant', 'refrigerantCharge', '', '', ''],
  ['Fan coil units, cassettes and split systems', 'fanCoil splitInstall', '', '', ''],
  ['Fans: exhaust, smoke exhaust and car park jet fans', 'jetFans', '', '', ''],
  ['Roof plant, cowls, flues and roof penetrations', 'roofPenetration', '', '', ''],
  ['Ductwork and pipework insulation', 'mechInsulation', 'ductwork mechPipework', '', 'insulating ductwork is not installing it'],
  ['BMS and controls', 'controlPanelInstall', '', '', ''],
  ['In-ground mechanical pipework and pits', 'trench', '', '', ''],
  ['Testing, commissioning and air balancing', 'mechCommissioning', '', '', ''],
  ['Core drilling, chasing and sealing penetrations', 'coreDrill', '', '', ''],
  ['Disconnecting, removing and reconnecting existing plant', 'servicesStrip', '', '', ''],
  ['Service and maintenance of installed plant', 'defectsVisit|acService|mechCommissioning', 'plantService', '', 'building plant, not mobile plant'],
  // Painting
  ['Internal painting by brush and roller', 'painting', '', '', ''],
  ['External painting at height', 'paintExternal', '', '', ''],
  ['Airless spray painting and solvent-based coatings', 'paintSpray', '', '', ''],
  ['Preparing existing painted surfaces: lead paint, abrasive and water blasting', 'leadPaint abrasiveBlast hydroBlast', '', '', ''],
  ['Protective coatings to steel and concrete', 'painting|paintSpray', '', '', ''],
  // Piling
  ['Piling rig delivery, assembly and working platform', 'pilingPlatform', '', '', ''],
  ['CFA piling', 'pilingRig', '', '', ''],
  ['Bored piles with temporary casing or support fluid', 'pilingRig openBore', '', '', ''],
  ['Driven piles: precast concrete and steel', 'drivenPiles', '', '', ''],
  ['Sheet piling: install and extract', 'drivenPiles', 'pilingRig', '', 'sheet piles are vibrated or driven, not drilled'],
  ['Screw piles', '', 'pilingRig drivenPiles', 'gap', 'screw piles'],
  ['Secant, contiguous and soldier pile walls', 'pilingRig|shoringWall', '', '', ''],
  ['Pile trimming and pile head breakdown', 'pileTrim', '', '', ''],
  ['Pile load and integrity testing', '', 'pilingRig', 'gap', 'pile load and integrity testing'],
  ['Ground improvement with a rig: stone columns, rigid inclusions and wick drains', 'groundImprove', '', '', ''],
  ['Marine piling from a barge or jack-up', 'marinePlant water', '', '', ''],
  // Pipelines and drainage
  ['Stormwater drainage: pipes, pits and subsoil drains', 'trench', '', '', ''],
  ['Gravity sewer mains and manholes', 'trench', '', '', ''],
  ['Connections to live sewers and work in existing manholes', 'sewerConnection confined', '', '', ''],
  ['Water mains: lay, test, disinfect and connect', 'trench waterConnection', '', '', ''],
  ['Live water main connections and shutdowns', 'waterConnection', '', '', ''],
  ['Pump stations, wet wells and valve chambers', 'tankPlace|pumpInstall', '', '', ''],
  ['Culverts and headwalls', 'trench|tankPlace', '', '', ''],
  ['Trenchless crossings: directional drilling, boring and pipe jacking', 'hddBore', '', '', ''],
  ['Pipe relining, cleaning and CCTV inspection', 'pipeRelining', '', '', ''],
  ['Stormwater basins, open channels and swales', 'earthworks', '', '', ''],
  // Plasterboard, walls and ceilings
  ['Steel stud framing to walls, bulkheads and ceilings', 'carpFraming', '', '', ''],
  ['Plasterboard and fibre cement linings to walls, partitions and ceilings', 'plasterSheets', '', '', ''],
  ['Setting, sanding and finishing plasterboard', 'plasterSanding', '', '', ''],
  ['Suspended grid and acoustic tile ceilings', 'ceilingGrid', '', '', ''],
  ['Insulated sandwich wall and ceiling panels', '', 'wallPanels', 'gap', 'insulated sandwich panel walls in a fit-out (the coolroom step is for coolrooms)'],
  ['Shaft walls and fire rated walls', 'carpFraming|plasterSheets', '', '', ''],
  ['External wall framing, soffits and fibre cement facade sheeting', 'carpFraming', '', '', ''],
  ['Lead-lined walls and radiation shielding', 'leadShielding', '', '', ''],
  // Plumbing and hydraulics
  ['In-ground sewer and stormwater drainage on the building site', 'trench', '', '', ''],
  ['Connections to live sewer, stormwater and water mains', 'sewerConnection waterConnection', '', '', ''],
  ['Under-slab drainage and cast-in sleeves', 'underslabDrainage castInPlumbing', '', '', ''],
  ['Sanitary stacks, water and hot water pipework at height', 'hydraulicRisers', '', '', ''],
  ['Plumbing rough-in and fit-off of fixtures', 'plumbingFitOff', '', '', ''],
  ['Hot water plant, pumps and water tanks', 'waterHeater|pumpInstall|tankPlace|boilerPlant', '', '', ''],
  ['Sewer pump stations, grease traps and pits, including confined space entry', 'confined', '', '', ''],
  ['Gas services: natural gas and LPG', 'gasFitting', '', '', ''],
  ['Pressure testing, flushing and commissioning', 'pressureTest', '', '', ''],
  ['Roof drainage: downpipes, rainwater heads and siphonic outlets', 'gutters', '', '', ''],
  ['Core drilling, chasing and sealing penetrations', 'coreDrill', '', '', ''],
  ['Isolating, capping and removing existing services', 'servicesStrip', '', '', ''],
  ['Temporary site plumbing and drainage', '', '', 'gap', 'temporary site plumbing and drainage'],
  // Precast
  ['Precast and tilt-up wall panels: lift, stand, brace and grout', 'precast', 'tileMix tileCut tileLay', '', 'grouting a panel base is not tiling'],
  ['Precast columns, beams, stairs and landings', 'precast|precastStair', '', '', ''],
  ['Precast floor units: hollowcore, planks, rib and tee floors', 'precastFloor', '', '', ''],
  ['Precast seating units on rakers', 'precastTier', '', '', ''],
  ['Volumetric precast modules and pods', 'moduleInstall', '', '', ''],
  // Rail
  ['Rail safeworking and track protection (protection officer)', 'railCorridor', '', '', ''],
  ['Track construction: sleepers, rail, ballast, tamping', 'trackWork', '', '', ''],
  ['Resleepering and ballast renewal', 'trackWork', '', '', ''],
  ['Rail welding and stressing (aluminothermic and flash butt)', '', 'stressing', 'gap', 'rail welding and rail stressing (not post-tensioning)'],
  ['Turnout installation and renewal', 'trackWork', '', '', ''],
  ['Road-rail (hi-rail) plant operation', '', '', 'gap', 'road-rail (hi-rail) plant'],
  ['Rail corridor civil works: drainage, access roads and fencing', 'railCorridor', '', '', ''],
  ['Level crossing renewal', 'railCorridor road', '', '', ''],
  ['Station platform works next to live track', 'railCorridor', '', '', ''],
  // Retaining walls
  ['Gabion walls', 'retainingWall', '', '', 'the retaining wall group has a gabion basket step'],
  ['Segmental block, concrete sleeper and reinforced soil walls', 'retainingWall', 'reo', '', 'reinforced soil is geogrid, not reo'],
  ['Cast in situ concrete retaining walls', 'concreteWall', '', '', ''],
  ['Precast concrete retaining walls and reinforced earth panels', 'precast|retainingWall', 'reo', '', 'reinforced earth is geogrid or straps, not reo'],
  ['Soil nailing and shotcrete walls', 'shotcrete', '', '', ''],
  ['Ground anchors and rock bolts', 'anchorsProps|drillRig', '', '', ''],
  ['Crib walls', 'retainingWall', '', '', ''],
  ['Rock walls and rock armour', 'rockLining', '', '', ''],
  // Roads and pavements
  ['Subgrade preparation and proof rolling', 'earthworks', '', '', ''],
  ['Granular pavement layers: sub-base and base', 'gravelLay|roadPlant', '', '', ''],
  ['Pavement stabilisation (lime, cement or foamed bitumen)', 'roadPlant', '', '', ''],
  ['Asphalt paving', 'asphaltLay', '', '', ''],
  ['Asphalt profiling (milling)', 'roadPlant', '', '', ''],
  ['Sprayed bitumen sealing', 'sprayRoad', '', '', ''],
  ['Concrete road pavement (slipform paving)', 'slabGround|concrete', 'paving', '', 'slipform paving is concrete, not pavers'],
  ['Concrete kerb and channel', 'kerbInstall', '', '', ''],
  ['Concrete footpaths, shared paths and driveways', 'slabGround slabPour', '', '', ''],
  ['Saw cutting and pavement reinstatement', 'sawCut|asphalt', '', '', ''],
  ['Line marking and raised pavement markers', 'lineMarking', '', '', ''],
  ['Road safety barrier, signs and guide posts', 'roadBarrier', '', '', ''],
  ['Noise walls', 'noiseWall', '', '', ''],
  // Roofing and cladding
  ['Metal roof sheeting, safety mesh, blanket and flashings', 'roof', '', '', ''],
  ['Re-roofing and roof sheet replacement on existing buildings', 'roofStrip roof', '', '', ''],
  ['Metal wall cladding', 'claddingInstall', '', '', ''],
  ['Skylights, roof penetrations and plant flashings', 'roofPenetration|skylight', '', '', ''],
  ['Permanent roof safety systems: guardrail, walkways, anchors and static lines', 'anchorInstall', '', '', ''],
  // Scaffolding
  ['Fixed scaffold: erect, alter and dismantle (modular and tube and coupler)', 'scaffold', '', '', ''],
  ['Hung, cantilevered and suspended scaffolds, including swing stages', 'swingStage', '', '', ''],
  ['Birdcage and load-bearing support scaffolds', 'scaffold|formwork', '', '', ''],
  ["Builders' hoists: install, climb and dismantle", 'hoistInstall', '', '', ''],
  ["Builders' hoist operation", 'hoistOperate', '', '', ''],
  ['Temporary edge protection, stair towers and safety nets', 'safetyNet edgeProtectionInstall|tempStairs', '', '', ''],
  ['Mast climbing work platforms: install and dismantle', '', '', 'gap', 'installing and dismantling mast climbing work platforms (it ticks the swing stage step as a near match)'],
  // Shared access and handling
  ['Using an elevating work platform (scissor lift or boom lift)', 'ewp', '', '', ''],
  ['Erecting and dismantling mobile scaffolds', 'mobileScaffold', '', '', ''],
  ['Using mobile scaffolds', 'mobileScaffold', '', '', ''],
  ['Using ladders (step, platform and extension)', 'ladderUse', '', '', ''],
  ['Manual handling', '', '', 'general', ''],
  ['Forklifts and telehandlers', 'forklift', '', '', ''],
  ['Pallet jacks, electric pallet jacks and walkie stackers', '', '', 'general', 'plant item'],
  ['Power tools, including explosive powered tools', 'pdtFixing', '', '', ''],
  ['Working at heights: harnesses, travel restraint and fall arrest', '', '', 'general', ''],
  // Shopfitting
  ['Tenancy fit-out: whole shopfitting package', '', '', 'general', 'whole trade'],
  ['Shopfront hoarding and working in an operating centre', 'siteEstablish', '', '', ''],
  ['Tenancy strip-out and make good', 'officeStrip|stripOut', '', '', ''],
  ['Shopfitting joinery, counters and display units', 'carpJoinery', '', '', ''],
  ['Tenancy partitions, ceilings and bulkheads', 'carpFraming', '', '', ''],
  ['Shopfronts, signage and display lighting', 'signageInstall|glassHandle', '', '', ''],
  // Site establishment and traffic
  ['Temporary fencing, hoardings and gates', 'siteEstablish', '', '', ''],
  ['Site sheds and amenities: deliver, place, connect and remove', 'siteSheds', '', '', ''],
  ['Gantries and overhead protection over footpaths', 'siteEstablish', '', '', ''],
  ['Traffic management on public roads', 'road', 'heavyHaulage', '', 'traffic management is not haulage'],
  ['Site traffic and plant movement management', 'sitePlant', '', '', ''],
  // Steel fixing and post-tensioning
  ['Reinforcement to footings, pile caps, ground slabs and pits', 'reo', '', '', ''],
  ['Reinforcement on suspended slabs and beams', 'reo', '', '', ''],
  ['Reinforcement to walls, columns and cores, and prefabricated cages', 'reo', '', '', ''],
  ['Post-tensioning: placing ducts, strand and anchorages', 'ptTendons', '', '', ''],
  ['Post-tensioning: stressing, grouting and cutting tails', 'stressing', 'tileCut tileMix tileLay', '', 'grouting tendon ducts is not tiling'],
  ['De-stressing and cutting into post-tensioned slabs', '', '', 'gap', 'de-stressing and cutting into post-tensioned slabs (it ticks the stressing steps as a near match)'],
  // Structural steel
  ['Structural steel erection: columns, beams, rafters, purlins and bracing', 'steelErect', '', '', ''],
  ['Metal floor decking and shear stud welding', 'deckingStuds', '', '', ''],
  ['Long span and heavy steel: dual lifts and temporary support towers', 'dualLift', '', '', ''],
  ['Secondary steel: stairs, platforms, walkways, handrails and grid mesh', 'accessSteel', '', '', ''],
  ['Steel strengthening and alterations in existing buildings', 'beamInstall|steelErect', '', '', ''],
  // Tiling
  ['Floor and wall tiling', 'tileLay', '', '', ''],
  ['Floor screeds, toppings and bedding', 'tileMix', '', '', ''],
  ['Balcony, terrace and roof top tiling', 'tileEdge', '', '', ''],
  ['Stone and large format floor tiles', 'tileLay', '', '', ''],
  ['Pool, wet deck and coping tiling', 'tileLay', '', '', ''],
  // Waterproofing
  ['Wet area membranes: bathrooms, kitchens and plant rooms', 'wpLiquid', '', '', ''],
  ['Balcony, podium, planter and trafficable deck membranes', 'wpLiquid wpEdge', '', '', ''],
  ['Roof membranes: torch-on and liquid applied', 'wpTorch', '', '', ''],
  ['Basement tanking, lift pits and below ground walls', 'belowGroundWp', '', '', ''],
  ['Pools, tanks and water retaining structures', '', '', 'general', 'names no waterproofing: the title alone does not say what work'],
  ['Sealants, caulking and expansion joints', 'caulking', '', '', ''],
];

const PROBE = [
  ['Conduit installation, in ground', 'trench', '', '', ''],
  ['Conduit installation, walls and ceilings', 'fitOff', '', '', ''],
  ['Installation of switchboards', 'commissioning', '', '', ''],
  ['Installation of submains', 'cablePull', '', '', ''],
  ['Working in risers', '', '', 'gap', 'work in open service risers'],
  ['Installation of fibre optic cable', 'fibre', '', '', ''],
  ['Energise and commission installation', 'commissioning', '', '', ''],
  ['Test and tag electrical equipment', 'testTag', '', '', ''],
  ['Installing duct work to underside of concrete', 'ductwork', '', '', ''],
  ['Installing pair coil refrigerant piping', 'mechPipework|refrigerantPipework', '', '', ''],
  ['Installing condensate piping', 'mechPipework', '', '', ''],
  ['Installing FCU to concrete', 'fanCoil', '', '', ''],
  ['Rough ins', '', '', 'general', ''],
  ['Removals of air conditioners', 'servicesStrip', '', '', ''],
  ['Sewer main and manholes', 'trench', '', '', ''],
  ['Water main installation, pressure test and disinfect', 'trench waterConnection', '', '', ''],
  ['Pipe laying in trenches', 'trench', '', '', ''],
  ['Hydraulics rough in and fit off', 'plumbingFitOff', '', '', ''],
  ['Site clearing, grubbing and topsoil stripping', 'vegClearing', '', '', ''],
  ['Detailed excavation for footings and pile caps', 'detailDig', '', '', ''],
  ['Rock breaking', 'rockBreak', '', '', ''],
  ['Erosion and sediment controls', '', '', 'gap', 'erosion and sediment controls'],
  ['Vacuum excavation to locate services', 'vacExcavation', '', '', ''],
  ['Kerb and channel', 'kerbInstall', '', '', ''],
  ['Line marking', 'lineMarking', '', '', ''],
  ['Sprayed bitumen seal', 'sprayRoad', '', '', ''],
  ['Concrete footpaths', 'slabGround slabPour', '', '', ''],
  ['Screw piles', '', 'pilingRig drivenPiles', 'gap', 'screw piles'],
  ['Sheet piling', 'drivenPiles', 'pilingRig', '', ''],
  ['Driven piles', 'drivenPiles', '', '', ''],
  ['Pile trimming', 'pileTrim', '', '', ''],
  ['Jumpform', 'jumpform', '', '', ''],
  ['Core walls formwork', 'formwork|jumpform', '', '', ''],
  ['Formwork supply and fix', 'formwork', '', '', ''],
  ['Delivery of concrete', '', '', 'gap', 'concrete agitator truck delivery'],
  ['Concrete boom pumping', 'concrete', '', '', ''],
  ['Steel erection, purlins, girts and cladding', 'steelErect', '', '', ''],
  ['Grid mesh removal', '', '', 'gap', 'removing floor grid mesh and checker plate'],
  ['Brick and block laying', 'masonryLay', '', '', ''],
  ['Floor and wall tiling', 'tileLay', '', '', ''],
  ['Painting', 'painting', '', '', ''],
  ['Window installation', 'windowInstall', '', '', ''],
  ['Curtain wall installation', 'panelInstall|glassHandle', '', '', ''],
  ['Fix and eave carpentry', 'carpJoinery', '', '', ''],
  ['Shopfitting', '', '', 'general', 'whole trade'],
  ['Under slab insulation', 'insulation', '', '', ''],
  ['Install insulated wall panels', '', 'wallPanels', 'gap', 'insulated sandwich panel walls in a fit-out'],
  ['Hazardous tree removal with chainsaws', 'treeRemoval', '', '', ''],
  ['Vegetation clearing and mulching', 'vegClearing', '', '', ''],
  ['Water truck operation', 'earthworks', '', '', ''],
  ['Crane truck in the rail corridor', 'loaderCrane railCorridor', '', '', ''],
  ['Loading and unloading mobile plant', 'heavyHaulage', '', '', ''],
  ['Friable asbestos removal', 'asbestos', '', '', ''],
  ['Non-friable asbestos removal', 'asbestos', '', '', ''],
  ['Track resleepering', 'trackWork', '', '', ''],
  ['Bridge bearings replacement', 'bridgeBearings', '', '', ''],
  ['Gabion walls', 'retainingWall', '', '', ''],
  ['Soil nailing and shotcrete', 'shotcrete', '', '', ''],
  ['Sparky rough in', 'fitOff', '', '', ''],
  ['Lay pipes', 'trench', '', '', ''],
  ['Pour footings', 'slabGround|concrete', '', '', ''],
  ['Strip out', 'stripOut|officeStrip', '', '', ''],
  ['Install sprinkler heads', 'fireAtHeight', 'ceilingPipework', '', ''],
  ['Hang plasterboard', 'plasterSheets', '', '', ''],
  ['Tie reo', 'reo', '', '', ''],
];

const toRow = ([typed, want, not, type, note]) => ({
  typed,
  // Each group is a list of kinds, any one of which will do.
  want: want ? want.split(' ').map((group) => group.split('|')) : [],
  not: not ? not.split(' ') : [],
  type: type || 'task',
  note,
});

module.exports = { TITLES: TITLES.map(toRow), LABELS: LABELS.map(toRow), PROBE: PROBE.map(toRow) };
