// Australian site slang and shorthand, read the way it is meant before the job steps are
// picked. The SWMS keeps the task as the user typed it. Each change gives words the rest
// of SiteReady already knows, and reading a task twice gives the same result.
const SLANG = [
  // Shorthand
  [/\bw\/(?=\s|$)/gi, 'with '],
  [/\bw\/(?=\w)/gi, 'with '],
  [/\bthru\b/gi, 'through'],
  [/\binst(?:al)?\b/gi, 'install'],
  [/\brd\b/gi, 'road'],
  [/\bhwy\b/gi, 'highway'],
  [/\bmwy\b/gi, 'motorway'],
  [/\bfwy\b/gi, 'freeway'],
  [/\bdia\b/gi, 'diameter'],
  [/\blvl\b/gi, 'level'],
  [/\bL(\d{1,3})\b/g, 'level $1'],
  [/\bcar ?park\b/gi, 'car park'],
  [/\bTC\b/g, 'tower crane'],
  [/\bMEWPs?\b/g, 'EWP'],
  [/\bPT (slabs?|beams?|bands?)\b/g, 'post-tensioned $1'],
  [/\bRCP\b/g, 'reinforced concrete pipe'],
  [/\bRCBCs?\b/g, 'reinforced concrete box culvert'],
  [/\bGPOs?\b/g, 'power points'],
  [/\bs\/s\b|\bSS\b/g, 'stainless steel'],
  [/\bpenos?\b/gi, 'penetrations'],
  [/\bpowerlines?\b/gi, 'power lines'],
  // Asbestos cement: "AC pipe" or "AC sheet" is asbestos cement. "AC pipework" and "AC unit" are air conditioning.
  [/\bAC (pipes?|mains?|sheets?|sheeting)\b/g, 'asbestos cement $1'],
  [/\baircon\b|\ba\/c\b/gi, 'air conditioning'],
  [/\bAC (units?|systems?)\b/g, 'air conditioning $1'],
  // Demolition
  [/\bdemo'?d\b/gi, 'demolished'],
  [/\bdemo(?:'?ing)\b/gi, 'demolishing'],
  [/\bdemo\b(?!nstrat)/gi, 'demolish'],
  // Trades
  [/\bsparkies\b/gi, 'electricians'],
  [/\bsparky\b/gi, 'electrician'],
  [/\bchippies\b/gi, 'carpenters'],
  [/\bchippy\b/gi, 'carpenter'],
  [/\bbrickies\b/gi, 'bricklayers'],
  [/\bbrickie\b/gi, 'bricklayer'],
  [/\bscaffies\b/gi, 'scaffolders'],
  [/\bscaffy\b/gi, 'scaffolder'],
  [/\bsubbies\b/gi, 'subcontractors'],
  [/\bsubbie\b/gi, 'subcontractor'],
  // Plant and gear known by brand
  [/\bkangas?\b/gi, 'jackhammer'],
  [/\bdingos?\b/gi, 'mini loader'],
  [/\bhi-?abs?\b/gi, 'vehicle loading crane'],
  [/\bacrows?\b/gi, 'props'],
  [/\bdunn(?:y|ies)\b/gi, 'toilets'],
  // How SWMS titles are worded: "Installation of switchboards" is installing them, "duct work"
  // is ductwork and "storm water" is stormwater.
  [/\binstall(?:at)?ion of\b/gi, 'install'],
  [/\bduct work\b/gi, 'ductwork'],
  [/\bstorm water\b/gi, 'stormwater'],
  [/\bsub soil\b/gi, 'subsoil'],
  [/\belevated work platform/gi, 'elevating work platform'],
  [/\b((?:de-?)?energi)([zZ])(e|ed|es|ing|ation)\b/gi, (word, start, z, end) => `${start}${z === 'Z' ? 'S' : 's'}${end}`],
  [/ & /g, ' and '],
  [/\bposi tracks?\b/gi, 'posi-track'],
  [/\brefrigerate (pip(?:e|es|ing|ework)|lines?)\b/gi, 'refrigerant $1'],
  [/\bair condition (units?)\b/gi, 'air conditioning $1'],
  [/\bhydraulics\b/gi, 'hydraulic services'],
  // How subbies type on a phone: shorthand, words run together or split, and common slips.
  [/\btemp(?= (?:power|lighting|lights?|generators?|fenc\w*|bridges?|works?|plumbing|water|sewer|toilets?|amenities|sheds?|stairs?|edge|hoardings?|boards?|services?|roads?|access|supply|supplies)\b)/gi, 'temporary'],
  [/\bgenn(?:y|ies)\b|\bgensets?\b/gi, 'generator'],
  [/\bhook ?ups?\b/gi, 'hook up'],
  [/\bAHU(s?)\b/g, 'air handling unit$1'],
  [/\bFCU(s?)\b/g, 'fan coil unit$1'],
  [/\bCHW\b/g, 'chilled water'],
  [/\bHHW\b/g, 'heating hot water'],
  [/\bHWU(s?)\b/g, 'hot water unit$1'],
  [/\bMSB(s?)\b/g, 'main switchboard$1'],
  [/\bDB(s?)\b/g, 'distribution board$1'],
  [/\bSOG\b/g, 'slab on ground'],
  [/\bNDD\b/g, 'non-destructive digging'],
  [/\bnon destructive\b/gi, 'non-destructive'],
  [/\bTGSIs?\b/g, 'tactile indicators'],
  [/\bRE (walls?|panels?)\b/g, 'reinforced earth $1'],
  [/\bFC (sheet\w*|cladding|boards?|linings?|panels?)\b/g, 'fibre cement $1'],
  [/\bACM (cladding|panels?|sheets?|facades?)\b/g, 'aluminium composite $1'],
  // "PT" on its own is post-tensioning; "PT slab" is read above.
  [/\bPT\b/g, 'post-tensioning'],
  [/\belec\b/gi, 'electrical'],
  [/\bmech\b/gi, 'mechanical'],
  [/\bconc\b/gi, 'concrete'],
  [/\bscaff\b/gi, 'scaffold'],
  [/\bhydro(?= (?:rough|fit|pipework|pipes|piping|risers?|services|stacks?|plumbing|fit-?out|reticulation)\b)/gi, 'hydraulic'],
  [/\bhydro test(s|ing)?\b/gi, 'hydrostatic test$1'],
  [/\bair con\b/gi, 'air conditioning'],
  [/\b(old|existing|the) AC\b/g, '$1 air conditioning'],
  [/\bfitoffs?\b/gi, 'fit off'],
  [/\broughins?\b/gi, 'rough in'],
  [/\bstripouts?\b/gi, 'strip out'],
  [/\bin ?ground\b(?! (?:floors?|levels?|storeys?|bearing|conditions))/gi, 'in-ground'],
  [/\bline ?marking\b/gi, 'line marking'],
  [/\bwater ?main(s?)\b/gi, 'water main$1'],
  [/\bsteel ?fix(ing|er|ers)\b/gi, 'steel fix$1'],
  [/\bearth works\b/gi, 'earthworks'],
  [/\bfalse work\b/gi, 'falsework'],
  [/\bfork lift(s?)\b/gi, 'forklift$1'],
  [/\bsky light(s?)\b/gi, 'skylight$1'],
  [/\bdown pipe(s?)\b/gi, 'downpipe$1'],
  [/\bfoot path(s?)\b/gi, 'footpath$1'],
  [/\bpre cast\b/gi, 'precast'],
  [/\btilt up\b/gi, 'tilt-up'],
  [/\bshot crete\b/gi, 'shotcrete'],
  [/\bsub station(s?)\b/gi, 'substation$1'],
  [/\bsub grade\b/gi, 'subgrade'],
  [/\bbird cage\b/gi, 'birdcage'],
  [/\bplay ground(s?)\b/gi, 'playground$1'],
  [/\bswing ?stage(s?)\b/gi, 'swing stage$1'],
  [/\bjump form(s?)\b/gi, 'jumpform$1'],
  [/\bhollow core\b/gi, 'hollowcore'],
  [/\bre (roof\w*|sheet\w*|point\w*)\b/gi, 're$1'],
  [/\breroof/gi, 're-roof'],
  [/\bre-(lin\w*|point\w*)\b/gi, 're$1'],
  [/\bin ?situ\b/gi, 'in situ'],
  [/\bpilling\b/gi, 'piling'],
  [/\bpost tension(\w*)/gi, 'post-tension$1'],
  [/\bsub[- ]mains?\b/gi, (word) => word.replace(/[- ]/, '')],
  [/\bwater proof(\w*)/gi, 'waterproof$1'],
  [/\brock brak(e|es|ing)\b/gi, 'rock break$1'],
  [/\blightening (?=(?:protection|conductors?|rods?|strikes?|arrestors?)\b)/gi, 'lightning '],
  [/\bcurb(?=(?:s|ing)?(?: and (?:channel|gutter)| machine)\b)/gi, 'kerb'],
  [/\bsteal (?=(?:erect\w*|beams?|columns?|frames?|framing|work|fix\w*|fabricat\w*|structures?|studs?|purlins?|decking)\b)/gi, 'steel '],
  [/\btest (?:n|'n'|n') tag\b|\btag (?:and|&|n) test\b/gi, 'test and tag'],
  [/\b(stabili|moderni|mobili)z(e|es|ed|ing|ation)\b/gi, '$1s$2'],
  [/\bgern(?:i|ie|y)(?:s|ing|ed)?\b/gi, 'pressure clean'],
  [/\bfrannas?\b(?! cranes?)/gi, (word) => `${word} crane`],
  [/\bdongas?\b/gi, 'site shed'],
  [/\blite (?=(?:poles?|fittings?|towers?)\b)/gi, 'light '],
  [/\bclen\b/gi, 'clean'],
  [/\bduel (?=lifts?\b)/gi, 'dual '],
  [/\bspay (?=(?:foam|paint\w*|insulation|seal\w*)\b)/gi, 'spray '],
  [/\bwal\b/gi, 'wall'],
  [/\btrey\b/gi, 'tray'],
  // Trade words used as verbs before what they are done to: "Membrane the shower bases", "Tank the
  // basement walls", "Glaze the shopfronts", "Plant out the median", "Frame the
  // walls", "Form the deck", "Concrete the stairs", "Mark out the courts", "Insulate the roof".
  [/\bmembrane (?=(?:the|all|each|both)\b)/gi, 'waterproof '],
  [/\btank (?=(?:the|all|each|both)\b)/gi, 'apply tanking to '],
  [/\bglaze (?=(?:the|all|each|both)\b)/gi, 'fit the glass to '],
  [/\bplant(?: out)? (?=(?:the|all|each|both)\b)(?!the (?:room|deck|rooms|equipment)\b)/gi, 'planting '],
  [/\bframe (?=(?:the|all|each|both)\b)(?!the (?:door|window)s?\b)/gi, 'build framing to '],
  [/(^|[.;:]\s*)form(?=,\s*(?:reo|reinforce)\b)/gi, '$1formwork'],
  [/(^|[.;:]\s*|\band\s+|\bthen\s+)form (?=(?:the|all|each|both)\b)(?![^.]*\bwith (?:blocks?|bricks?|masonry|pavers?|stone|sleepers?)\b)/gi, '$1erect formwork to '],
  [/(^|[.;:]\s*|\band\s+|\bthen\s+)concrete (?=(?:the|all|each|both)\b)/gi, '$1pour concrete to '],
  [/\bmark out (?=(?:the|all|each|both)\b)/gi, 'line mark '],
  [/\binsulate (?=(?:the|all|each|both)\b)/gi, 'fit insulation to '],
  // "Tilling" is tiling unless the task is about soil.
  [/\btilling\b/gi, (word, at, whole) => (/\b(?:soil|garden|lawns?|turf|rotary|hoe|beds?|landscap\w*|paddocks?)\b/i.test(whole) ? word : 'tiling')],
];

function readSlang(text) {
  let out = String(text || '');
  for (const [pattern, replacement] of SLANG) out = out.replace(pattern, replacement);
  return out.replace(/\s+/g, ' ').trim();
}

module.exports = { readSlang };
